# NOTE: THIS COMPOSE FILE IS ONLY MEANT FOR DEVELOPMENT. PRODUCTION WILL BE USING KUBERNETES. Production database will be on Azure SQL (a managed SQL)
services:
  # Development services will be added here.
  auth_service:
    build:
      context: .
      dockerfile: services/auth_services/Dockerfile
    container_name: auth-server
    env_file: '.env'
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${AUTH_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PASSWORD_SALT: ${PASSWORD_SALT}
      AUTH_PORT: ${AUTH_PORT}
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:15-alpine
    container_name: database-server
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${AUTH_DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: '.env'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      LISTING_DB_NAME: ${LISTING_DB_NAME}
      RESERVATION_DB_NAME: ${RESERVATION_DB_NAME}
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
      - ./scripts/dev/init-scripts:/docker-entrypoint-initdb.d

volumes:
  auth_pgdata:
