# NOTE:
# THIS COMPOSE FILE IS ONLY MEANT FOR DEVELOPMENT. PRODUCTION WILL BE USING KUBERNETES.
# Production database will be on Azure Database for PostgreSQL

x-common-api-environment: &common-api-environment
  AUTH_SERVICE_URL: http://auth_service:8000
  LISTING_SERVICE_URL: http://listing_service:8000
  RESERVATION_SERVICE_URL: http://reservation_service:8000

x-common-vite-environment: &common-vite-environment
  VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
  VITE_LISTING_SERVICE_URL: ${VITE_LISTING_SERVICE_URL}
  VITE_RESERVATION_SERVICE_URL: ${VITE_RESERVATION_SERVICE_URL}
  VITE_SAMPLE_SERVICE_URL: ${VITE_SAMPLE_SERVICE_URL}

x-common-db-environment: &common-db-environment
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  PASSWORD_SALT: ${PASSWORD_SALT}

x-common-backend-environment: &common-backend-environment
  CORS_ORIGIN_URL: ${CORS_ORIGIN_URL}

services:
  # Development services will be added here.
  frontend_service:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        <<:
          - *common-vite-environment
    container_name: frontend-server
    env_file: '.env'
    ports:
      - '${FRONTEND_PORT:-8000}:80'
    environment:
      <<:
        - *common-api-environment

  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth-server
    env_file: '.env'
    ports:
      - '${AUTH_PORT:-8001}:8000'
    environment:
      <<:
        - *common-db-environment
        - *common-api-environment
        - *common-backend-environment
      DB_NAME: ${AUTH_DB_NAME}
    depends_on:
      auth_migrate:
        condition: service_completed_successfully

  sample_service:
    build:
      context: .
      dockerfile: services/sample_service/Dockerfile
    container_name: sample-server
    env_file: '.env'
    ports:
      - '${SAMPLE_PORT:-8001}:8000'
    environment:
      <<:
        - *common-db-environment
        - *common-api-environment
        - *common-backend-environment
      DB_NAME: ${SAMPLE_DB_NAME}
    depends_on:
      postgresql:
        condition: service_healthy

  auth_migrate:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    command: ['python', '-m', 'app.migrate']
    env_file: '.env'
    environment:
      <<:
        - *common-db-environment
      DB_NAME: ${AUTH_DB_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
    restart: 'no'

  postgresql:
    image: postgres:15-alpine
    container_name: database-server
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${DB_USER} -d $${AUTH_DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: '.env'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      AUTH_DB_NAME: ${AUTH_DB_NAME}
      LISTING_DB_NAME: ${LISTING_DB_NAME}
      RESERVATION_DB_NAME: ${RESERVATION_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/dev/init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
