apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sample-service

  template:
    metadata:
      labels:
        app: sample-service

    spec:
      containers:
        - name: sample-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"